In [1]:
## Chemin vers l'espace de travail
## ici le dossier Data -- Pensez à bien indiquer cela avec RStudio 
setwd("../Data")

############### Stations Météo France ###############################
####### lecture et chargement des données quotidiennes ################
#####################################################################

mydataMF <- read.csv("Q_21_previous-1950-2024_RR-T-Vent.csv.gz", sep = ";")
class(mydataMF) ## Classe de l'objet
str(mydataMF) ## structure de l'objet avec le type des données contenues

[1] "data.frame"

'data.frame':	1530067 obs. of  60 variables:
 $ NUM_POSTE   : int  21010001 21010001 21010001 21010001 21010001 21010001 21010001 21010001 21010001 21010001 ...
 $ NOM_USUEL   : chr  "ALOXE CORTON" "ALOXE CORTON" "ALOXE CORTON" "ALOXE CORTON" ...
 $ LAT         : num  47.1 47.1 47.1 47.1 47.1 ...
 $ LON         : num  4.86 4.86 4.86 4.86 4.86 ...
 $ ALTI        : int  273 273 273 273 273 273 273 273 273 273 ...
 $ AAAAMMJJ    : int  19570101 19570102 19570103 19570104 19570105 19570106 19570107 19570108 19570109 19570110 ...
 $ RR          : num  0 0 1.5 0 0 1.4 0 0 0 4 ...
 $ QRR         : int  9 9 9 9 9 9 9 9 9 9 ...
 $ TN          : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QTN         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ HTN         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QHTN        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ TX          : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QTX         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ HTX         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QHTX        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ TM          : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QTM         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ TNTXM       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QTNTXM      : int  NA NA NA NA NA NA NA NA NA NA ...
 $ TAMPLI      : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QTAMPLI     : int  NA NA NA NA NA NA NA NA NA NA ...
 $ TNSOL       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QTNSOL      : int  NA NA NA NA NA NA NA NA NA NA ...
 $ TN50        : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QTN50       : int  NA NA NA NA NA NA NA NA NA NA ...
 $ DG          : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QDG         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ FFM         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QFFM        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ FF2M        : logi  NA NA NA NA NA NA ...
 $ QFF2M       : logi  NA NA NA NA NA NA ...
 $ FXY         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QFXY        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ DXY         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QDXY        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ HXY         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QHXY        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ FXI         : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QFXI        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ DXI         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QDXI        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ HXI         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QHXI        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ FXI2        : logi  NA NA NA NA NA NA ...
 $ QFXI2       : logi  NA NA NA NA NA NA ...
 $ DXI2        : logi  NA NA NA NA NA NA ...
 $ QDXI2       : logi  NA NA NA NA NA NA ...
 $ HXI2        : logi  NA NA NA NA NA NA ...
 $ QHXI2       : logi  NA NA NA NA NA NA ...
 $ FXI3S       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ QFXI3S      : int  NA NA NA NA NA NA NA NA NA NA ...
 $ DXI3S       : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QDXI3S      : int  NA NA NA NA NA NA NA NA NA NA ...
 $ HXI3S       : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QHXI3S      : int  NA NA NA NA NA NA NA NA NA NA ...
 $ DRR         : int  NA NA NA NA NA NA NA NA NA NA ...
 $ QDRR        : int  NA NA NA NA NA NA NA NA NA NA ...
 $ STATUS_FXI3S: int  NA NA NA NA NA NA NA NA NA NA ...
 $ STATUS_DXI3S: int  NA NA NA NA NA NA NA NA NA NA ...

In [2]:
## Exploration des données Météo-France##
########################################################
head(mydataMF) ## affichage les premières lignes des données
tail(mydataMF) ## affichage des dernières lignes des données
dim(mydataMF) ## dimension de l'objet

  NUM_POSTE NOM_USUEL    LAT    LON    ALTI AAAAMMJJ RR  QRR TN QTN ⋯ FXI3S
1 21010001  ALOXE CORTON 47.069 4.8615 273  19570101 0.0 9   NA NA  ⋯ NA
2 21010001  ALOXE CORTON 47.069 4.8615 273  19570102 0.0 9   NA NA  ⋯ NA
3 21010001  ALOXE CORTON 47.069 4.8615 273  19570103 1.5 9   NA NA  ⋯ NA
4 21010001  ALOXE CORTON 47.069 4.8615 273  19570104 0.0 9   NA NA  ⋯ NA
5 21010001  ALOXE CORTON 47.069 4.8615 273  19570105 0.0 9   NA NA  ⋯ NA
6 21010001  ALOXE CORTON 47.069 4.8615 273  19570106 1.4 9   NA NA  ⋯ NA
  QFXI3S DXI3S QDXI3S HXI3S QHXI3S DRR QDRR STATUS_FXI3S STATUS_DXI3S
1 NA     NA    NA     NA    NA     NA  NA   NA           NA
2 NA     NA    NA     NA    NA     NA  NA   NA           NA
3 NA     NA    NA     NA    NA     NA  NA   NA           NA
4 NA     NA    NA     NA    NA     NA  NA   NA           NA
5 NA     NA    NA     NA    NA     NA  NA   NA           NA
6 NA     NA    NA     NA    NA     NA  NA   NA           NA

        NUM_POSTE NOM_USUEL     LAT      LON      ALTI AAAAMMJJ RR QRR TN QTN ⋯
1530062 21714001  VOSNE ROMANEE 47.16183 4.954167 255  20190625 0  1   NA NA  ⋯
1530063 21714001  VOSNE ROMANEE 47.16183 4.954167 255  20190626 0  1   NA NA  ⋯
1530064 21714001  VOSNE ROMANEE 47.16183 4.954167 255  20190627 0  1   NA NA  ⋯
1530065 21714001  VOSNE ROMANEE 47.16183 4.954167 255  20190628 0  1   NA NA  ⋯
1530066 21714001  VOSNE ROMANEE 47.16183 4.954167 255  20190629 0  1   NA NA  ⋯
1530067 21714001  VOSNE ROMANEE 47.16183 4.954167 255  20190630 0  1   NA NA  ⋯
        FXI3S QFXI3S DXI3S QDXI3S HXI3S QHXI3S DRR QDRR STATUS_FXI3S
1530062 NA    NA     NA    NA     NA    NA     NA  NA   NA
1530063 NA    NA     NA    NA     NA    NA     NA  NA   NA
1530064 NA    NA     NA    NA     NA    NA     NA  NA   NA
1530065 NA    NA     NA    NA     NA    NA     NA  NA   NA
1530066 NA    NA     NA    NA     NA    NA     NA  NA   NA
1530067 NA    NA     NA    NA     NA    NA     NA  NA   NA
        STATUS_DXI3S
1530062 NA
1530063 NA
1530064 NA
1530065 NA
1530066 NA
1530067 NA

[1] 1530067      60

In [3]:
###########################################################
## Identification du nombre de stations Météo-France
###########################################################
MFposte <- unique(mydataMF[, c("NUM_POSTE", "NOM_USUEL", "LAT", "LON", "ALTI")])
head(MFposte) ## Affichage des premières lignes des données
dim(MFposte)
write.csv(MFposte,file="MFposte21.csv")

       NUM_POSTE NOM_USUEL          LAT      LON      ALTI
1      21010001  ALOXE CORTON       47.06900 4.861500 273
21949  21012001  AMPILLY LE SEC     47.80833 4.529000 277
47959  21023001  ARNAY LE DUC       47.13333 4.493333 365
65004  21030001  AUBAINE            47.16667 4.703833 380
87222  21038001  AUXONNE            47.19017 5.380000 185
109137 21043001  BAIGNEUX LES JUIFS 47.60033 4.645167 415

[1] 111   5

In [4]:
## Nettoyage des données i.e. suppression/conservation des certaines colonnes
## pour cela on s'aide du fichier "Q_descriptif_champs_RR-T-Vent.csv"
## récupéré sur le site https://meteo.data.gouv.fr/

mydataMF <- mydataMF[, c("NUM_POSTE", "AAAAMMJJ", "RR", "TN", "TX")]
dim(mydataMF)
str(mydataMF)

[1] 1530067       5

'data.frame':	1530067 obs. of  5 variables:
 $ NUM_POSTE: int  21010001 21010001 21010001 21010001 21010001 21010001 21010001 21010001 21010001 21010001 ...
 $ AAAAMMJJ : int  19570101 19570102 19570103 19570104 19570105 19570106 19570107 19570108 19570109 19570110 ...
 $ RR       : num  0 0 1.5 0 0 1.4 0 0 0 4 ...
 $ TN       : num  NA NA NA NA NA NA NA NA NA NA ...
 $ TX       : num  NA NA NA NA NA NA NA NA NA NA ...

In [5]:
## Quel est le format de données de la colonne qui contient les dates ? ##
## création d'un vecteur date nécessaire pour créer un objet xts

mydates <- as.Date(as.character(mydataMF$AAAAMMJJ), "%Y%m%d")
## Chargement de la librairie xts
library(xts)

Le chargement a nécessité le package : zoo


Attachement du package : ‘zoo’


Les objets suivants sont masqués depuis ‘package:base’:

    as.Date, as.Date.numeric

In [6]:
mydataMF.xts <- xts(mydataMF[, c("NUM_POSTE","TN", "TX", "RR")], order.by = mydates)
dim(mydataMF.xts)

[1] 1530067       4

In [7]:
## Ici on découpe la période d'intérêt
mydataMF.xts <- mydataMF.xts["1976/2005"]
dim(mydataMF.xts)
length(unique(mydataMF.xts$NUM_POSTE))

[1] 718564      4

[1] 97

In [8]:
## Attention les données sont maintenant ordonnées selon les dates et non les stations
## vérifier cela
tail(mydataMF.xts)

           NUM_POSTE   TN  TX  RR
2005-12-31  21638002 -6.4 3.9 6.8
2005-12-31  21648001   NA  NA 5.7
2005-12-31  21656001   NA  NA 4.0
2005-12-31  21685001   NA  NA 9.8
2005-12-31  21710004   NA  NA 6.7
2005-12-31  21714001   NA  NA 3.3

In [9]:
## Boucle pour calculer les moyennes mensuelles pour chaque station
## et pour les trois variables climatiques Tn, Tx, RR

## Création d'objets vides que l'on va remplir par le calcul
## 3 objets pour les moyennes et 3 pour sélectionner les stations
## avec suffisamment de données et peu/pas de NA

dfnatx <- c();dftx <- c()
dfnatn <- c();dftn <- c()
dfnarr <- c();dfrr <- c()

for (i in MFposte$NUM_POSTE) {
  print(i)## affiche le numéro de la station MF qui est traitée
  tmp <- mydataMF.xts[mydataMF.xts$NUM_POSTE %in% i]

  if (nrow(tmp) == 0) { ## si la station n'a pas de données pour la période 1975/2005
    dfnatx <- cbind(dfnatx, NA)
    dfnatn <- cbind(dfnatn, NA)
    dfnarr <- cbind(dfnarr, NA)
    dftx <- cbind(dftx, NA)
    dftn <- cbind(dftn, NA)
    dfrr <- cbind(dfrr, NA)
  } else { 
    ## On calcule le nombre de NA pour chaque variable et pour chaque mois
    tmpna <- apply.monthly(
        tmp[, c("TN", "TX", "RR")],
        function(x) apply(x, 2, function(x) length(which(is.na(x))))
      )
    ## On rempli les objets pour avoir le nombre de NA par station, par mois et par variable
    dfnatx <- cbind(dfnatx, tmpna$TX)
    dfnatn <- cbind(dfnatn, tmpna$TN)
    dfnarr <- cbind(dfnarr, tmpna$RR)
        
    ## On calcule les moyennes mensuelles pour les températures 
    tmpst <- apply.monthly(tmp[, c("TN", "TX")],
      FUN = function(x) colMeans(x, na.rm = TRUE)
    )
    ## On rempli les objets avec les résultats
    dftx <- cbind(dftx, tmpst$TX)
    dftn <- cbind(dftn, tmpst$TN)
    
    ## On calcule les cumuls mensuels
    tmpstr <- apply.monthly(tmp[, c("RR")],
      FUN = function(x) colSums(x, na.rm = TRUE)
    )
    dfrr <- cbind(dfrr, tmpstr$RR)
  }
}

[1] 21010001
[1] 21012001
[1] 21023001
[1] 21030001
[1] 21038001
[1] 21043001
[1] 21054001
[1] 21054002
[1] 21056001
[1] 21065001
[1] 21068001
[1] 21109001
[1] 21116002
[1] 21131001
[1] 21139001
[1] 21142001
[1] 21146001
[1] 21154001
[1] 21154002
[1] 21164002
[1] 21196001
[1] 21228001
[1] 21231001
[1] 21231002
[1] 21231006
[1] 21231007
[1] 21237001
[1] 21271001
[1] 21277001
[1] 21292001
[1] 21296001
[1] 21299001
[1] 21304002
[1] 21308001
[1] 21310001
[1] 21312001
[1] 21317001
[1] 21321001
[1] 21326001
[1] 21332001
[1] 21336001
[1] 21349001
[1] 21351001
[1] 21357001
[1] 21357002
[1] 21361001
[1] 21380001
[1] 21382001
[1] 21382002
[1] 21383001
[1] 21384001
[1] 21386001
[1] 21390001
[1] 21395001
[1] 21396001
[1] 21406001
[1] 21409001
[1] 21410001
[1] 21419001
[1] 21425001
[1] 21441001
[1] 21445001
[1] 21446001
[1] 21449001
[1] 21454001
[1] 21461001
[1] 21461002
[1] 21464001
[1] 21471001
[1] 21473001
[1] 21484001
[1] 21497001
[1] 21501001
[1] 21501003
[1] 21503001
[1] 21515001
[1] 21517001
[1] 21519001
[1] 21525001
[1] 21527001
[1] 21546001
[1] 21546011
[1] 21560001
[1] 21561001
[1] 21561003
[1] 21564001
[1] 21567001
[1] 21569001
[1] 21573001
[1] 21584001
[1] 21589001
[1] 21590001
[1] 21603001
[1] 21603003
[1] 21611001
[1] 21633001
[1] 21633002
[1] 21638002
[1] 21648001
[1] 21656001
[1] 21663001
[1] 21676001
[1] 21685001
[1] 21690001
[1] 21699001
[1] 21705001
[1] 21710001
[1] 21710004
[1] 21711001
[1] 21713001
[1] 21714001

In [10]:
## le calcul renvoie des NaN si que des NA dans la série
## On les remplace par des NA
dftn[dftn == "NaN"] <- NA; dfnatn[dfnatn == "NaN"] <- NA
dftx[dftx == "NaN"] <- NA; dfnatx[dfnatx == "NaN"] <- NA
dfrr[dfrr == "NaN"] <- NA; dfnarr[dfnarr == "NaN"] <- NA

class(dftx)
dim(dftx)
head(dftx)
tail(dftx)

[1] "xts" "zoo"

[1] 377 111

           TX TX.1 TX.2 TX.3      TX.4      TX.5 TX.6 NA. TX.7 TX.8 TX.9 TX.10
1976-01-31 NA   NA   NA   NA  4.683871  4.025806   NA  NA   NA   NA   NA    NA
1976-02-29 NA   NA   NA   NA  5.465517  7.458621   NA  NA   NA   NA   NA    NA
1976-03-31 NA   NA   NA   NA 10.177419 10.038710   NA  NA   NA   NA   NA    NA
1976-04-30 NA   NA   NA   NA 14.290000 14.006667   NA  NA   NA   NA   NA    NA
1976-05-31 NA   NA   NA   NA 19.800000 20.454839   NA  NA   NA   NA   NA    NA
1976-06-30 NA   NA   NA   NA 26.633333 26.483333   NA  NA   NA   NA   NA    NA
           NA..1 TX.11 TX.12 TX.13 TX.14     TX.15 NA..2 TX.16     TX.17
1976-01-31    NA    NA    NA    NA    NA  4.906452    NA    NA  5.822581
1976-02-29    NA    NA    NA    NA    NA  7.827586    NA    NA  7.189655
1976-03-31    NA    NA    NA    NA    NA 11.148387    NA    NA 12.232258
1976-04-30    NA    NA    NA    NA    NA 14.866667    NA    NA 16.816667
1976-05-31    NA    NA    NA    NA    NA 21.280645    NA    NA 22.825806
1976-06-30    NA    NA    NA    NA    NA 27.803333    NA    NA 29.083333
               TX.18 TX.19 TX.20 TX.21 TX.22 TX.23 TX.24     TX.25 TX.26 TX.27
1976-01-31  3.954839    NA    NA    NA    NA    NA    NA  5.012903    NA    NA
1976-02-29  6.213793    NA    NA    NA    NA    NA    NA  6.141379    NA    NA
1976-03-31  9.419355    NA    NA    NA    NA    NA    NA 11.258065    NA    NA
1976-04-30 13.863333    NA    NA    NA    NA    NA    NA 16.163333    NA    NA
1976-05-31 19.445161    NA    NA    NA    NA    NA    NA 21.932258    NA    NA
1976-06-30 26.363333    NA    NA    NA    NA    NA    NA 28.263333    NA    NA
           TX.28 TX.29 TX.30 TX.31 TX.32 TX.33 TX.34 NA..3 TX.35 TX.36 TX.37
1976-01-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-02-29    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-03-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-04-30    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-05-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-06-30    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
           TX.38 NA..4 TX.39 TX.40 TX.41 TX.42 TX.43 TX.44 TX.45 TX.46
1976-01-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-02-29    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-03-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-04-30    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-05-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-06-30    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
               TX.47 NA..5 TX.48 TX.49 NA..6 TX.50 TX.51 TX.52 TX.53 TX.54
1976-01-31  5.774194    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-02-29  6.489655    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-03-31 11.577419    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-04-30 16.436667    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-05-31 22.332258    NA    NA    NA    NA    NA    NA    NA    NA    NA
1976-06-30 29.380000    NA    NA    NA    NA    NA    NA    NA    NA    NA
           TX.55 TX.56 TX.57 TX.58 TX.59 TX.60 TX.61     TX.62 TX.63 TX.64
1976-01-31    NA    NA    NA    NA    NA    NA    NA  5.406452    NA    NA
1976-02-29    NA    NA    NA    NA    NA    NA    NA  6.068966    NA    NA
1976-03-31    NA    NA    NA    NA    NA    NA    NA 11.261290    NA    NA
1976-04-30    NA    NA    NA    NA    NA    NA    NA 15.880000    NA    NA
1976-05-31    NA    NA    NA    NA    NA    NA    NA 21.403226    NA    NA
1976-06-30    NA    NA    NA    NA    NA    NA    NA 27.773333    NA    NA
           TX.65 TX.66 TX.67 TX.68 NA..7 TX.69 TX.70     TX.71 TX.72 TX.73
1976-01-31    NA    NA    NA    NA    NA    NA    NA  4.109677    NA    NA
1976-02-29    NA    NA    NA    NA    NA    NA    NA  6.096552    NA    NA
1976-03-31    NA    NA    NA    NA    NA    NA    NA  9.709677    NA    NA
1976-04-30    NA    NA    NA    NA    NA    NA    NA 14.350000    NA    NA
1976-05-31    NA    NA    NA    NA    NA    NA    NA 19.887097    NA    NA
1976-06-30    NA    NA    NA    NA    NA    NA    NA 26.333333    NA    NA
           TX.74 TX.75 TX.76     TX.77 TX.78 NA..8 NA..9     TX.79 TX.80
1976-01-31    NA    NA    NA  5.641935    NA    NA    NA  4.661290    NA
1976-02-29    NA    NA    NA  6.341379    NA    NA    NA  6.513793    NA
1976-03-31    NA    NA    NA 11.432258    NA    NA    NA  9.312903    NA
1976-04-30    NA    NA    NA 16.000000    NA    NA    NA 12.623333    NA
1976-05-31    NA    NA    NA 21.490323    NA    NA    NA 18.961290    NA
1976-06-30    NA    NA    NA 28.066667    NA    NA    NA 25.043333    NA
               TX.81 TX.82 NA..10 TX.83 NA..11 NA..12 TX.84 TX.85 TX.86 TX.87
1976-01-31  5.316129    NA     NA    NA     NA     NA    NA    NA    NA    NA
1976-02-29  5.824138    NA     NA    NA     NA     NA    NA    NA    NA    NA
1976-03-31 10.838710    NA     NA    NA     NA     NA    NA    NA    NA    NA
1976-04-30 15.593333    NA     NA    NA     NA     NA    NA    NA    NA    NA
1976-05-31 21.045161    NA     NA    NA     NA     NA    NA    NA    NA    NA
1976-06-30 27.656667    NA     NA    NA     NA     NA    NA    NA    NA    NA
           TX.88 TX.89 TX.90 NA..13 TX.91 TX.92 TX.93 TX.94 TX.95 TX.96
1976-01-31    NA    NA    NA     NA    NA    NA    NA    NA    NA    NA
1976-02-29    NA    NA    NA     NA    NA    NA    NA    NA    NA    NA
1976-03-31    NA    NA    NA     NA    NA    NA    NA    NA    NA    NA
1976-04-30    NA    NA    NA     NA    NA    NA    NA    NA    NA    NA
1976-05-31    NA    NA    NA     NA    NA    NA    NA    NA    NA    NA
1976-06-30    NA    NA    NA     NA    NA    NA    NA    NA    NA    NA

           TX TX.1 TX.2 TX.3     TX.4     TX.5 TX.6 NA. TX.7      TX.8 TX.9
2005-07-31 NA   NA   NA   NA 27.23226 24.70000   NA  NA   NA 23.416129   NA
2005-08-31 NA   NA   NA   NA 25.60323 23.45484   NA  NA   NA 22.041935   NA
2005-09-30 NA   NA   NA   NA       NA 21.86333   NA  NA   NA 20.193333   NA
2005-10-31 NA   NA   NA   NA 20.27097 18.76129   NA  NA   NA 16.554839   NA
2005-11-30 NA   NA   NA   NA  9.02000  8.39000   NA  NA   NA  6.290000   NA
2005-12-31 NA   NA   NA   NA       NA  3.33871   NA  NA   NA  2.296774   NA
           TX.10 NA..1     TX.11 TX.12 TX.13 TX.14     TX.15 NA..2 TX.16 TX.17
2005-07-31    NA    NA 26.787097    NA    NA    NA 24.851613    NA    NA    NA
2005-08-31    NA    NA 24.996774    NA    NA    NA 23.893548    NA    NA    NA
2005-09-30    NA    NA 23.183333    NA    NA    NA 22.570000    NA    NA    NA
2005-10-31    NA    NA 19.667742    NA    NA    NA 19.851613    NA    NA    NA
2005-11-30    NA    NA  8.623333    NA    NA    NA  8.666667    NA    NA    NA
2005-12-31    NA    NA  4.474194    NA    NA    NA  4.148387    NA    NA    NA
           TX.18 TX.19 TX.20 TX.21     TX.22 TX.23 TX.24 TX.25 TX.26 TX.27
2005-07-31    NA    NA    NA    NA 26.796774    NA    NA    NA    NA    NA
2005-08-31    NA    NA    NA    NA 24.680645    NA    NA    NA    NA    NA
2005-09-30    NA    NA    NA    NA 23.266667    NA    NA    NA    NA    NA
2005-10-31    NA    NA    NA    NA 19.070968    NA    NA    NA    NA    NA
2005-11-30    NA    NA    NA    NA  8.493333    NA    NA    NA    NA    NA
2005-12-31    NA    NA    NA    NA  4.300000    NA    NA    NA    NA    NA
           TX.28 TX.29 TX.30 TX.31 TX.32 TX.33 TX.34 NA..3 TX.35 TX.36 TX.37
2005-07-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-08-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-09-30    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-10-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-11-30    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-12-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
           TX.38 NA..4 TX.39 TX.40 TX.41 TX.42 TX.43 TX.44 TX.45 TX.46
2005-07-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-08-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-09-30    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-10-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-11-30    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2005-12-31    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
               TX.47 NA..5 TX.48 TX.49 NA..6 TX.50 TX.51     TX.52 TX.53 TX.54
2005-07-31 27.351613    NA    NA    NA    NA    NA    NA 25.616129    NA    NA
2005-08-31 25.516129    NA    NA    NA    NA    NA    NA 24.574194    NA    NA
2005-09-30 23.550000    NA    NA    NA    NA    NA    NA 22.793333    NA    NA
2005-10-31 19.241935    NA    NA    NA    NA    NA    NA 20.012903    NA    NA
2005-11-30  8.416667    NA    NA    NA    NA    NA    NA  9.253333    NA    NA
2005-12-31  4.419355    NA    NA    NA    NA    NA    NA  4.796774    NA    NA
           TX.55 TX.56 TX.57 TX.58 TX.59 TX.60 TX.61     TX.62 TX.63 TX.64
2005-07-31    NA    NA    NA    NA    NA    NA    NA 26.767742    NA    NA
2005-08-31    NA    NA    NA    NA    NA    NA    NA 24.845161    NA    NA
2005-09-30    NA    NA    NA    NA    NA    NA    NA 23.200000    NA    NA
2005-10-31    NA    NA    NA    NA    NA    NA    NA 19.190323    NA    NA
2005-11-30    NA    NA    NA    NA    NA    NA    NA  8.256667    NA    NA
2005-12-31    NA    NA    NA    NA    NA    NA    NA  4.167742    NA    NA
           TX.65     TX.66 TX.67     TX.68 NA..7 TX.69 TX.70     TX.71 TX.72
2005-07-31    NA 25.054839    NA 26.651613    NA    NA    NA 25.709677    NA
2005-08-31    NA 23.606452    NA 24.938710    NA    NA    NA 24.370968    NA
2005-09-30    NA 22.540000    NA 23.366667    NA    NA    NA 22.116667    NA
2005-10-31    NA 19.000000    NA 19.348387    NA    NA    NA 18.306452    NA
2005-11-30    NA  8.170000    NA  8.316667    NA    NA    NA  7.700000    NA
2005-12-31    NA  3.735484    NA  4.083871    NA    NA    NA  3.741935    NA
           TX.73     TX.74 TX.75     TX.76     TX.77    TX.78 NA..8 NA..9 TX.79
2005-07-31    NA 23.725806    NA 23.551613 27.529032 25.33226    NA    NA    NA
2005-08-31    NA 22.516129    NA 21.758065 25.361290 23.86452    NA    NA    NA
2005-09-30    NA 21.073333    NA 20.396667 24.010000 22.56000    NA    NA    NA
2005-10-31    NA 18.064516    NA 16.990323 19.896774 19.27419    NA    NA    NA
2005-11-30    NA  7.333333    NA  6.593333  8.993333  7.83000    NA    NA    NA
2005-12-31    NA  2.548387    NA  2.096774  4.890323  3.53871    NA    NA    NA
           TX.80     TX.81     TX.82 NA..10 TX.83 NA..11 NA..12     TX.84 TX.85
2005-07-31    NA 27.161290 25.619355     NA    NA     NA     NA 25.890323    NA
2005-08-31    NA 25.561290 24.464516     NA    NA     NA     NA 24.438710    NA
2005-09-30    NA 23.376667 22.943333     NA    NA     NA     NA 23.140000    NA
2005-10-31    NA 19.587097 20.148387     NA    NA     NA     NA 18.767742    NA
2005-11-30    NA  8.733333  9.146667     NA    NA     NA     NA  7.956667    NA
2005-12-31    NA  4.667742  4.325806     NA    NA     NA     NA  3.800000    NA
           TX.86 TX.87 TX.88 TX.89 TX.90 NA..13 TX.91 TX.92 TX.93 TX.94 TX.95
2005-07-31    NA    NA    NA    NA    NA     NA    NA    NA    NA    NA    NA
2005-08-31    NA    NA    NA    NA    NA     NA    NA    NA    NA    NA    NA
2005-09-30    NA    NA    NA    NA    NA     NA    NA    NA    NA    NA    NA
2005-10-31    NA    NA    NA    NA    NA     NA    NA    NA    NA    NA    NA
2005-11-30    NA    NA    NA    NA    NA     NA    NA    NA    NA    NA    NA
2005-12-31    NA    NA    NA    NA    NA     NA    NA    NA    NA    NA    NA
           TX.96
2005-07-31    NA
2005-08-31    NA
2005-09-30    NA
2005-10-31    NA
2005-11-30    NA
2005-12-31    NA

In [11]:
## nettoyage des données, on enlève les mois incomplets
##
indom <- which(as.numeric(format(index(dftx), format = "%d")) < 28)
dftx <- dftx[-indom, ]; dfnatx <- dfnatx[-indom, ]
indom <- which(as.numeric(format(index(dftn), format = "%d")) < 28)
dftn <- dftn[-indom, ]; dfnatn <- dfnatn[-indom, ]
indom <- which(as.numeric(format(index(dfrr), format = "%d")) < 28)
dfrr <- dfrr[-indom, ]; dfnarr <- dfnarr[-indom, ]
###################################################################

In [12]:
## calcul des moyennes mensuelles toutes années confondus
## initalise les objets pour l'ensemble des résultats

## Création d'une fonction pour écarter les stations & mois incomplets
##
MFclean <- function(myxts, myxtsna){

  ## identifie les mois avec plus de 5 jours sans données
  ## et ceux avec des NA
  ind <- which(myxtsna > 5 | is.na(myxtsna))

  myxts[ind] <- NA
  
  mwna <- length(which(is.na(myxts)))
  ## si mwna > 60 i.e. plus de 5 ans sans données (12*5)
  ## alors tout en NA pour écarter la station
  if(mwna>60){
    myxts[] <- NA
  }
 return(myxts)
}
ls()

 [1] "dfnarr"       "dfnatn"       "dfnatx"       "dfrr"         "dftn"
 [6] "dftx"         "i"            "indom"        "MFclean"      "MFposte"
[11] "mydataMF"     "mydataMF.xts" "mydates"      "tmp"          "tmpna"
[16] "tmpst"        "tmpstr"

In [13]:
## Boucle principale du calcul des moyennes climatologiques période 1975/2005
resuMFTn <- c()
resuMFTx <- c()
resuMFRR <- c()
for (i in 1:ncol(dftn)){## boucle su les station qui sont en colonne
  tmptn <- MFclean(dftn[, i], dfnatn[, i])
  tmptx <- MFclean(dftx[, i], dfnatx[, i])
  tmprr <- MFclean(dfrr[, i], dfnarr[, i])
  ## initialise objet vide pour les moyennes mensuelles
  rmoiTn <- c()
  rmoiTx <- c()
  rmoiRR <- c()
  for (j in 1:12) {## boucle pous faire la moyenne de tous les mois de janvier, puis février etc.
    moi <- tmptn[.indexmon(tmptn) %in% (j - 1)]
    rmoiTn <- cbind(rmoiTn, colMeans(moi, na.rm = TRUE))
    moi <- tmptx[.indexmon(tmptx) %in% (j - 1)]
    rmoiTx <- cbind(rmoiTx, colMeans(moi, na.rm = TRUE))
    moi <- tmprr[.indexmon(tmprr) %in% (j - 1)]
    rmoiRR <- cbind(rmoiRR, colMeans(moi, na.rm = TRUE))
  }
  resuMFTn <- rbind(resuMFTn, rmoiTn)
  resuMFTx <- rbind(resuMFTx, rmoiTx)
  resuMFRR <- rbind(resuMFRR, rmoiRR)
}

In [19]:
head(resuMFTn)

     [,1]       [,2]       [,3]     [,4]     [,5]     [,6]     [,7]
TN          NaN        NaN      NaN      NaN      NaN      NaN      NaN
TN.1        NaN        NaN      NaN      NaN      NaN      NaN      NaN
TN.2        NaN        NaN      NaN      NaN      NaN      NaN      NaN
TN.3        NaN        NaN      NaN      NaN      NaN      NaN      NaN
TN.4 -0.1615054  0.3595731 2.883441 4.709778 9.053978 12.29233 14.05656
TN.5 -0.8594624 -0.5537274 1.807849 3.195556 7.149677 10.18189 12.13731
     [,8]     [,9]     [,10]    [,11]    [,12]
TN        NaN      NaN      NaN      NaN       NaN
TN.1      NaN      NaN      NaN      NaN       NaN
TN.2      NaN      NaN      NaN      NaN       NaN
TN.3      NaN      NaN      NaN      NaN       NaN
TN.4 13.79613 10.63184 7.765054 2.943889 1.0407119
TN.5 12.09032  9.39600 7.088817 2.265667 0.4626882

In [14]:
## Change les noms des colonnes
colnames(resuMFTn) <- month.abb
colnames(resuMFTx) <- month.abb
colnames(resuMFRR) <- month.abb

In [15]:
## fonction pour identifier les stations sans valeurs 
## afin de les écarter
MFind <- function(mydf) {
  ind <- which(apply(mydf, 1,
                     function(x) length(which(is.na(x)))) > 11)
  return(as.vector(ind))
}

In [16]:
## selection les stations des données
resuMFTn[resuMFTn == "NaN"] <- NA
ind <- MFind(resuMFTn)
resuMFTn <- resuMFTn[-ind, ]
MFTnposte <- MFposte[-ind,]

resuMFTx[resuMFTx == "NaN"] <- NA
ind <- MFind(resuMFTx)
resuMFTx <- resuMFTx[-ind, ]
MFTxposte <- MFposte[-ind, ]

resuMFRR[resuMFRR == "NaN"] <- NA
ind <- MFind(resuMFRR)
resuMFRR <- resuMFRR[-ind, ]
MFRRposte <- MFposte[-ind, ]

In [17]:
dim(resuMFTn)
dim(resuMFRR)
## Qu'en déduisez-vous à partir des dimension des objets qui contiennent les résultats ?
MFTxposte

[1] 10 12

[1] 45 12

        NUM_POSTE NOM_USUEL            LAT      LON      ALTI
87222   21038001  AUXONNE              47.19017 5.380000 185
109137  21043001  BAIGNEUX LES JUIFS   47.60033 4.645167 415
281181  21154001  CHATILLON/SEINE      47.84933 4.581333 262
742899  21390001  MARSANNAY LA COTE    47.26667 4.986833 280
945330  21473001  DIJON-LONGVIC        47.26783 5.088333 219
1115636 21527001  LA ROCHEPOT          46.95250 4.674000 417
1192376 21564001  ST NIC. CITEAUX      47.12217 5.072167 203
1239738 21584001  SAULIEU              47.26417 4.215000 586
1288823 21590001  SAVIGNY LES BEA      47.05633 4.836667 246
1315490 21603001  SEMUR EN AUXOIS_SAPC 47.48200 4.340000 314

In [18]:
save(resuMFRR,resuMFTn,resuMFTx,
     MFRRposte,MFTnposte,MFTxposte,
     file = "MFData_mois.RData")